#!/usr/bin/bash

# Job name:
#SBATCH --job-name=clump
# Project:
#SBATCH --account=p33
# Wall clock limit:
#SBATCH --time=24:20:00
#SBATCH --cpus-per-task=1
# Max memory usage:
#SBATCH --mem-per-cpu=8GB
#SBATCH --array=1-22


module purge
module load plink/1.90b6.2
source /cluster/projects/p33/users/mohammadzr/envs/pynext38/bin/activate


python /cluster/projects/p33/users/mohammadzr/neuroimmune_sleep/python_convert-master/sumstats.py clump --clump-field PVAL --force --sumstats ../../lipids/europeans/mostest/nmr_all_filtered45.mat.csv.most.orig.csv.gz --bfile-chr ../intermediate/chr@_unrelated_imp --exclude-ranges 6:25119106-33854733 8:7200000-12500000 --out nmr249_pheno45_clumped

echo 'Done'
